const produtos = [
  {
    id: 1,
    nome: "Pirelli Scorpion Verde All Season 235/60R16",
    imagem: "./images/pneus/Pirelli-Scorpion-Verde-All-Season-23560R16.jpg",
    marca: "Pirelli",
    logoMarca: "./images/pirelli.png",
    modelo: "Scorpion Verde All Season",
    medida: "235/60R16",
    largura: "235mm",
    perfil: "60%",
    aro: "16",
    diametro_total: "688.4 mm",
    indice_peso: "100 - 800 kg",
    indice_velocidade: "H - 210 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Assimétrico",
    tracao: "A",
    temperatura: "A",
    registro_inmetro: "001403/2012",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 699.90,
    precoParcelado: 777.70,
    avaliacao: 5,
    selo: "Mais Vendido", // ou "Em Oferta", ou "" para nenhum
    selo_inmetro: "./images/selos/Selo-Inmetro-Pirelli-Scorpion-Verde-All-Season-23560R16.png"
  },
  {
    id: 2,
    nome: "Bridgestone Ecopia EP150 195/55R16",
    imagem: "./images/pneus/Bridgestone-Ecopia-EP150-19555R16.jpg",
    marca: "Bridgestone",
    logoMarca: "./images/bridgestone.png",
    modelo: "Ecopia EP150",
    medida: "195/55R16",
    largura: "195mm",
    perfil: "55%",
    aro: "16",
    diametro_total: "620.9 mm",
    indice_peso: "87 - 545 kg",
    indice_velocidade: "V - 240 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Simétrico",
    tracao: "B",
    temperatura: "B",
    registro_inmetro: "002715/2012",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 689.90,
    precoParcelado: 766.56,
    avaliacao: 4,
    selo: "Em Oferta", // ou "Mais Vendido", ou "" para nenhum
    selo_inmetro: "./images/selos/Selo-Inmetro-Bridgestone-Ecopia-EP150-19555R16.jpg"
  },
  {
    id: 3,
    nome: "Firestone Destination LE2 235/60R16",
    imagem: "./images/pneus/Firestone-Destination-LE2-23560R16.jpg",
    marca: "Firestone",
    logoMarca: "./images/firestone.png",
    modelo: "Destination LE2",
    medida: "235/60R16",
    largura: "235mm",
    perfil: "60%",
    aro: "16",
    diametro_total: "688.4 mm",
    indice_peso: "100 - 800 kg, 100",
    indice_velocidade: "V - 240 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Assimétrico",
    tracao: "---", // Não Encontrado
    temperatura: "---", // Não Encontrado
    registro_inmetro: "---", // Não Encontrado
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 829.90,
    precoParcelado: 922.11, 
    avaliacao: 5,
    selo: "",
    selo_inmetro: "./images/selos/Selo-Inmetro-Firestone-Destination-LE2-23560R16.jpg"
  },
  {
    id: 4,
    nome: "Pirelli Chrono (MO) 195/75R16C",
    imagem: "./images/pneus/Pirelli-Chrono-19575R16C.jpg",
    marca: "Pirelli",
    logoMarca: "./images/pirelli.png",
    modelo: "Chrono",
    medida: "195/75R16",
    largura: "195mm",
    perfil: "75%",
    aro: "16",
    diametro_total: "698.9 mm",
    indice_peso: "107 - 975 kg, 107",
    indice_velocidade: "R - 170 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "---",
    desenho: "---",
    tracao: "---",
    temperatura: "---",
    registro_inmetro: "001418/2012",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 1119.90,
    precoParcelado: 1244.33,
    avaliacao: 4,
    selo: "",
    selo_inmetro: "./images/selos/Selo-Inmetro-Pirelli-Chrono-19575R16C.jpg"
},
{
    id: 5,
    nome: "Itaro IT203 185/60R14",
    imagem: "./images/pneus/Itaro-IT203-18560R14.jpg",
    marca: "Itaro",
    logoMarca: "./images/itaro.png",
    modelo: "IT203",
    medida: "185/60R14",
    largura: "185mm",
    perfil: "60%",
    aro: "14",
    diametro_total: "651.6 mm",
    indice_peso: "82 - 475 kg, 82",
    indice_velocidade: "H - 210 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Assimétrico",
    tracao: "A",
    temperatura: "A", 
    registro_inmetro: "010110/2013",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 269.90,
    precoParcelado: 299.89,
    avaliacao: 3,
    selo: "",
    selo_inmetro: "./images/selos/Selo-Inmetro-Itaro-IT203-18560R14.png"
},
{
    id: 6,
    nome: "Itaro IT203 185/65R15",
    imagem: "./images/pneus/Itaro-IT203-18565R15.jpg",
    marca: "Itaro",
    logoMarca: "./images/itaro.png",
    modelo: "IT203",
    medida: "185/65R15",
    largura: "185mm",
    perfil: "65%",
    aro: "15",
    diametro_total: "677.0 mm",
    indice_peso: "88 - 560 kg, 88",
    indice_velocidade: "H - 210 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Assimétrico",
    tracao: "A",
    temperatura: "B",
    registro_inmetro: "010089/2013",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 299.90,
    precoParcelado: 333.22,
    avaliacao: 5,
    selo: "Mais Vendido",
    selo_inmetro: "./images/selos/Selo-Inmetro-Itaro-IT203-18565R15.png"
},
{
    id: 7,
    nome: "Itaro IT101 215/60R17",
    imagem: "./images/pneus/Itaro-IT101-21560R17.jpg",
    marca: "Itaro",
    logoMarca: "./images/itaro.png",
    modelo: "IT101",
    medida: "215/60R17",
    largura: "215mm",
    perfil: "60%",
    aro: "17",
    diametro_total: "775.8 mm",
    indice_peso: "96 - 710 kg, 96",
    indice_velocidade: "H - 210 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Simétrico",
    tracao: "A",
    temperatura: "A",
    registro_inmetro: "010110/2013",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 439.90,
    precoParcelado: 488.78,
    avaliacao: "4",
    selo: "",
    selo_inmetro: "./images/selos/Selo-Inmetro-Itaro-IT101-21560R17.png"
},
{
    id: 8,
    nome: "Goodyear Wrangler Fortitude HT 235/60R16",
    imagem: "./images/pneus/Goodyear-Wrangler-Fortitude-HT-23560R16.jpg",
    marca: "Goodyear",
    logoMarca: "./images/goodyear.png",
    modelo: "Wrangler Fortitude HT",
    medida: "235/60R16",
    largura: "235mm",
    perfil: "60%",
    aro: "16",
    diametro_total: "782.4 mm",
    indice_peso: "100 - 800 kg, 100",
    indice_velocidade: "H - 210 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Simétrico",
    tracao: "---",
    temperatura: "---",
    registro_inmetro: "001310/2012",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 824.90,
    precoParcelado: 916.56,
    avaliacao: 5,
    selo: "Mais Vendido",
    selo_inmetro: "./images/selos/Selo-Inmetro-Goodyear-Wrangler-Fortitude-HT-23560R16.jpg"
},
{
    id: 9,
    nome: "Goodyear Wrangler Fortitude HT 205/65R15",
    imagem: "./images/pneus/Goodyear-Wrangler-Fortitude-HT-20565R15.jpg",
    marca: "Goodyear",
    logoMarca: "./images/goodyear.png",
    modelo: "Wrangler Fortitude HT",
    medida: "205/65R15",
    largura: "205mm",
    perfil: "65%",
    aro: "15",
    diametro_total: "709.0 mm",
    indice_peso: "94 - 670 kg",
    indice_velocidade: "H - 210 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Simétrico",
    tracao: "---",
    temperatura: "---",
    registro_inmetro: "002995/2013",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 679.90,
    precoParcelado: 755.44,
    avaliacao: 3,
    selo: "Em Oferta",
    selo_inmetro: "./images/selos/Selo-Inmetro-Goodyear-Wrangler-Fortitude-HT-20565R15.jpg"
},
{
    id: 10,
    nome: "Goodyear Eagle F1 Asymmetric 2 SUV 255/50R19",
    imagem: "./images/pneus/Goodyear-Eagle-F1-Asymmetric-2-SUV-25550R19.jpg",
    marca: "Goodyear",
    logoMarca: "./images/goodyear.png",
    modelo: "Eagle F1 Asymmetric 2 SUV",
    medida: "255/50R19",
    largura: "255mm",
    perfil: "50%",
    aro: "19",
    diametro_total: "737.6 mm",
    indice_peso: "103 - 875 kg",
    indice_velocidade: "Y - 300 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Assimétrico",
    tracao: "A",
    temperatura: "A",
    registro_inmetro: "001298/2012",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 1974.90,
    precoParcelado: 2194.33,
    avaliacao: "1",
    selo: "",
    selo_inmetro: "./images/selos/Selo-Inmetro-Goodyear-Eagle-F1-Asymmetric-2-SUV-25550R19.png"
},
{
    id: 11,
    nome: "Goodyear Efficientgrip Performance 205/55R16",
    imagem: "./images/pneus/Goodyear-Efficientgrip-Performance-20555R16.jpg",
    marca: "Goodyear",
    logoMarca: "./images/goodyear.png",
    modelo: "Efficientgrip Performance",
    medida: "205/55R16",
    largura: "205mm",
    perfil: "55%",
    aro: "16",
    diametro_total: "631.9 mm",
    indice_peso: "91 - 615 kg",
    indice_velocidade: "V - 240 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Assimétrico",
    tracao: "---",
    temperatura: "---",
    registro_inmetro: "001313/2012",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 579.90,
    precoParcelado: 644.33,
    avaliacao: "5",
    selo: "Mais Vendido",
    selo_inmetro: "./images/selos/Selo-Inmetro-Goodyear-Efficientgrip-Performance-20555R16.jpg"
},
{
    id: 12,
    nome: "Goodyear Wrangler Duratrac 285/75R16",
    imagem: "./images/pneus/Goodyear-Wrangler-Duratrac-28575R16.jpg",
    marca: "Goodyear",
    logoMarca: "./images/goodyear.png",
    modelo: "Wrangler Duratrac",
    medida: "285/75R16",
    largura: "285mm",
    perfil: "75%",
    aro: "16",
    diametro_total: "833.9 mm",
    indice_peso: "126 - 1700 kg , 123 - 1550 kg , 126/123",
    indice_velocidade: "Q - 160 km/h",
    tipo_construcao: "Radial",
    tipo_terreno: "MT",
    desenho: "Simétrico",
    tracao: "---",
    temperatura: "---",
    registro_inmetro: "000982/2012",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 2274.90,
    precoParcelado: 2527.67,
    avaliacao: "2",
    selo: "",
    selo_inmetro: "./images/selos/Selo-Inmetro-Goodyear-Wrangler-Duratrac-28575R16.png"
},
{
    id: 13,
    nome: "Continental ContiSportContact 5 MO 245/35R18 92Y XL",
    imagem: "./images/pneus/Continental-ContiSportContact5-24535R18.jpg",
    marca: "Continental",
    logoMarca: "./images/continental.png",
    modelo: "ContiSportContact 5",
    medida: "245/35R18",
    largura: "245mm",
    perfil: "35%",
    aro: "18",
    diametro_total: "849.2 mm",
    indice_peso: "92 - 630 kg , 92",
    indice_velocidade: "Y - 300 km/h , Y",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Assimétrico",
    tracao: "---",
    temperatura: "---",
    registro_inmetro: "004120/2012",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 1699.90,
    precoParcelado: 1888.78,
    avaliacao: "4",
    selo: "Em Oferta",
    selo_inmetro: "./images/selos/Selo-Inmetro-Continental-ContiSportContact-5-24535R18.png"
},
{
    id: 14,
    nome: "Continental ContiCrossContact LX2 225/55R18",
    imagem: "./images/pneus/Continental-ContiCrossContact-LX2-22555R18.jpg",
    marca: "Continental",
    logoMarca: "./images/continental.png",
    modelo: "ContiCrossContact LX2",
    medida: "225/55R18",
    largura: "225mm",
    perfil: "55%",
    aro: "18",
    diametro_total: "704.7 mm",
    indice_peso: "98 - 750 kg , 98",
    indice_velocidade: "V - 240 km/h , V",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Simétrico",
    tracao: "---",
    temperatura: "---",
    registro_inmetro: "002010/2013",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 839.90,
    precoParcelado: 933.22,
    avaliacao: "5",
    selo: "",
    selo_inmetro: "./images/selos/Selo-Inmetro-Continental-ContiCrossContact-LX2-22555R18.png"
},
{
    id: 15,
    nome: "Continental EcoContact 6 185/60R15",
    imagem: "./images/pneus/Continental-EcoContact-6-18560R15.jpg",
    marca: "Continental",
    logoMarca: "./images/continental.png",
    modelo: "EcoContact 6",
    medida: "185/60R15",
    largura: "185mm",
    perfil: "60%",
    aro: "15",
    diametro_total: "677.0 mm",
    indice_peso: "88 - 560 kg , 88",
    indice_velocidade: "H - 210 km/h , H",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Assimétrico",
    tracao: "A",
    temperatura: "A",
    registro_inmetro: "004112/2012",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 499.90,
    precoParcelado: 555.44,
    avaliacao: "3",
    selo: "Em Oferta",
    selo_inmetro: "./images/selos/Selo-Inmetro-Continental-EcoContact-6-18560R15.png"
},
{
    id: 16,
    nome: "Barum Bravuris 5HM 225/45R17",
    imagem: "./images/pneus/Barum-Bravuris-5HM-22545R17.jpg",
    marca: "Barum",
    logoMarca: "./images/barum.png",
    modelo: "Bravuris 5HM",
    medida: "225/45R17",
    largura: "225mm",
    perfil: "45%",
    aro: "17",
    diametro_total: "791.8 mm",
    indice_peso: "94 - 670 kg , 94",
    indice_velocidade: "W - 270 km/h , W",
    tipo_construcao: "Radial",
    tipo_terreno: "HT",
    desenho: "Assimétrico",
    tracao: "---",
    temperatura: "---",
    registro_inmetro: "004120/2012",
    garantia: "5 anos Contra Defeito de Fabricação",
    precoPix: 419.90,
    precoParcelado: 466.56,
    avaliacao: "5",
    selo: "Em Oferta",
    selo_inmetro: "./images/selos/Selo-Inmetro-Barum-Bravuris-5HM-22545R17.png"
}
];
